  management:
    endpoints:
      web:
        exposure:
          include: '*'
  logging:
    level:
      org:
        springframework: debug
  spring:
    profiles:
      active: cola
  resources:
    database:
      jdbc: hola
      driver: lola
    ibm:
      saa:
        hostname: test
        password: test
